### ISSUE TITLE
'Add a list...' com layout quebrado

### ISSUE THREAD

**Issue by helton** [entirc/kanban-board#2]
'Add a list...' não está aparecendo sempre do lado direito. Quando adicionamos mais que 3 listas ele passa a ser exibido abaixo das listas.

Problema deve ser com o 'float: right'.

**Comment by angelorubin** [comment]
Então, a idéia era essa mesmo Helton, para não ficar barra de rolagem horizontal (o que particularmente eu não acho agradável). Mas caso prefiram podemos mudar para ir adicionando horizontalmente mesmo.

**Comment by helton** [comment]
Problema corrigido no [Pull Request 31](https://github.com/entirc/kanban-board/pull/31).
