### ISSUE TITLE
Border-shadow do último card não está aparecendo

### ISSUE THREAD

**Issue by helton** [entirc/kanban-board#28]
O último card de uma lista sempre está sem border-shadow.

<img width="569" alt="border-shadow bug" src="https://user-images.githubusercontent.com/3588665/30837502-b94e5e8c-a23b-11e7-84be-376de58603aa.png">

O problema deve ser o espaço disponível.

Um `margin-bottom` de pelo menos `1px` deve resolver o problema.

**Comment by angelorubin** [comment]
Aqui ta normal.
![border-shadow](https://user-images.githubusercontent.com/1530309/30857221-53687b24-a291-11e7-98d3-2c48ff3b6eae.png)

**Comment by helton** [comment]
@angelorubin, na branch master ainda está com problema.

Acho que esse screenshot é da sua versão local (com CSS já modificado). A versão modificada que você disponibilizou em http://kanban-board.surge.sh/ realmente não tem o problema.

Pode ser que ao subir a correção da issue #2 esse problema não ocorra mais. Nesse caso a gente pode fechar essa issue.

**Comment by helton** [comment]
[Pull Request 31](https://github.com/entirc/kanban-board/pull/31) (já mergeado) corrigiu esse bug.
A issue pode ser fechada.
